{% set name = "fps-jupyterlab" %}
{% set version = "0.0.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_jupyterlab-{{ version }}.tar.gz
  sha256: a86bd35c6b252636a41586bf29b65a3c9efc1c4620fd0dcae46cd1d5d97aa861

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps <1
    - fps-auth <1
    - fps-lab <1
    - jupyterlab >=3,<4

test:
  imports:
    - fps_jupyterlab

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  summary: An FPS plugin for the JupyterLab API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
