{% set name = "fps-jupyterlab" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_jupyterlab-{{ version }}.tar.gz
  sha256: b5919897282fb639a53123b15c8ef1b38e719a3ae9458c986cc39282c62b4a8b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.1.4,<1
    - jupyterlab >=4,<5

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_jupyterlab

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  summary: An FPS plugin for the JupyterLab API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
