{% set name = "fps-jupyterlab" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_jupyterlab-{{ version }}.tar.gz
  sha256: c4de7817c22bfe4d2e20bae4a3e295dff77105e92c021c3b6b322db253d01c44

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.7.0,<1
    - jupyterlab >=4,<5

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_jupyterlab

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  summary: An FPS plugin for the JupyterLab API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
