{% set name = "fps-jupyterlab" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_jupyterlab-{{ version }}.tar.gz
  sha256: 81c51fa34c4fc267ad74461a9c0fa8dd60e26b51efb5e11198c64ab2735f55b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.8.0,<0.9.0
    - jupyterlab-js >=4.4.2,<5

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_jupyterlab

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  summary: An FPS plugin for the JupyterLab API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
