{% set name = "fps-jupyterlab" %}
{% set version = "0.0.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_jupyterlab-{{ version }}.tar.gz
  sha256: 7182c1a8ed7aab28e06c5b1b0dca7288b6b850f82b7dad7267eefd6323f09497

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - fps >=0.0.8,<1
    - fps-auth-base <1
    - fps-frontend <1
    - fps-lab >=0.0.37,<1
    - jupyterlab >=3,<4

test:
  imports:
    - fps_jupyterlab

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  summary: An FPS plugin for the JupyterLab API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
